INSERT INTO tbl_tags VALUES (1, 'Emergência');
INSERT INTO tbl_tags VALUES (2, 'Black Friday');
INSERT INTO tbl_tags VALUES (3, 'Parcelado');
INSERT INTO tbl_tags VALUES (4, 'Impulso');
INSERT INTO tbl_tags VALUES (5, 'Planejado');
INSERT INTO tbl_tags VALUES (6, 'Cashback');
INSERT INTO tbl_tags VALUES (7, 'Viagem');

INSERT INTO tbl_categories VALUES (1, 'EXPENSE', 'Alimentação', 'pizza.svg');
INSERT INTO tbl_categories VALUES (2, 'EXPENSE', 'Compra', 'shopping-cart.svg');
INSERT INTO tbl_categories VALUES (3, 'EXPENSE', 'Educação', 'graduation-cap.svg');
INSERT INTO tbl_categories VALUES (4, 'EXPENSE', 'Lazer', 'mask-happy.svg');
INSERT INTO tbl_categories VALUES (5, 'EXPENSE', 'Moradia', 'house-line.svg');
INSERT INTO tbl_categories VALUES (6, 'EXPENSE', 'Outro', 'question-mark.svg');
INSERT INTO tbl_categories VALUES (7, 'EXPENSE', 'Pet', 'dog.svg');
INSERT INTO tbl_categories VALUES (8, 'EXPENSE', 'Saúde', 'first-aid.svg');
INSERT INTO tbl_categories VALUES (9, 'EXPENSE', 'Taxa e Imposto', 'scales.svg');
INSERT INTO tbl_categories VALUES (10, 'EXPENSE', 'Transporte', 'car-profile.svg');
INSERT INTO tbl_categories VALUES (11, 'EXPENSE', 'Vestimenta', 't-shirt.svg');
INSERT INTO tbl_categories VALUES (17, 'EXPENSE', 'Construção', 'bulldozer.svg');
INSERT INTO tbl_categories VALUES (18, 'EXPENSE', 'Estorno', 'currency-circle-dollar.svg');
INSERT INTO tbl_categories VALUES (19, 'EXPENSE', 'Serviço', 'call-bell.svg');
INSERT INTO tbl_categories VALUES (20, 'EXPENSE', 'Custo', 'pi.svg');
INSERT INTO tbl_categories VALUES (21, 'EXPENSE', 'Web', 'devices.svg');
INSERT INTO tbl_categories VALUES (12, 'INCOME', 'Salário', 'money.svg');
INSERT INTO tbl_categories VALUES (13, 'INCOME', 'Prestação de Serviço', 'call-bell.svg');
INSERT INTO tbl_categories VALUES (14, 'INCOME', 'Rendimento', 'chart-line-up.svg');
INSERT INTO tbl_categories VALUES (15, 'INCOME', 'Empréstimo', 'bank.svg');
INSERT INTO tbl_categories VALUES (16, 'INCOME', 'Venda', 'handshake.svg');

INSERT INTO tbl_subcategories VALUES (1, 1, 'Conveniência');
INSERT INTO tbl_subcategories VALUES (2, 1, 'Lanchonete');
INSERT INTO tbl_subcategories VALUES (3, 1, 'Restaurante');
INSERT INTO tbl_subcategories VALUES (4, 1, 'Outro');
INSERT INTO tbl_subcategories VALUES (5, 1, 'Supermercado');
INSERT INTO tbl_subcategories VALUES (6, 2, 'Equipamento');
INSERT INTO tbl_subcategories VALUES (7, 3, 'Curso');
INSERT INTO tbl_subcategories VALUES (8, 3, 'Livro');
INSERT INTO tbl_subcategories VALUES (9, 3, 'Mensalidade');
INSERT INTO tbl_subcategories VALUES (10, 7, 'Alimentação');
INSERT INTO tbl_subcategories VALUES (11, 7, 'Medicamento');
INSERT INTO tbl_subcategories VALUES (12, 7, 'Veterinário');
INSERT INTO tbl_subcategories VALUES (13, 8, 'Consulta');
INSERT INTO tbl_subcategories VALUES (14, 8, 'Medicamento');
INSERT INTO tbl_subcategories VALUES (15, 10, 'Combustível');
INSERT INTO tbl_subcategories VALUES (16, 10, 'Translado');
INSERT INTO tbl_subcategories VALUES (17, 10, 'Manutenção');
INSERT INTO tbl_subcategories VALUES (18, 13, 'Contrato');
INSERT INTO tbl_subcategories VALUES (19, 13, 'Particular');
INSERT INTO tbl_subcategories VALUES (20, 15, 'Bancário');
INSERT INTO tbl_subcategories VALUES (21, 15, 'Pessoal');
INSERT INTO tbl_subcategories VALUES (22, 2, 'Presente');
INSERT INTO tbl_subcategories VALUES (23, 2, 'Software');
INSERT INTO tbl_subcategories VALUES (24, 3, 'Assinatura');
INSERT INTO tbl_subcategories VALUES (25, 4, 'Evento');
INSERT INTO tbl_subcategories VALUES (26, 4, 'Viagem');
INSERT INTO tbl_subcategories VALUES (27, 5, 'Manutenção');
INSERT INTO tbl_subcategories VALUES (28, 7, 'Acessórios');
INSERT INTO tbl_subcategories VALUES (29, 8, 'Cuidados pessoais');
INSERT INTO tbl_subcategories VALUES (30, 8, 'Outro');
INSERT INTO tbl_subcategories VALUES (31, 8, 'Plano');
INSERT INTO tbl_subcategories VALUES (32, 19, 'Bancário');
INSERT INTO tbl_subcategories VALUES (33, 19, 'Contabilidade');
INSERT INTO tbl_subcategories VALUES (34, 10, 'Estacionamento');
INSERT INTO tbl_subcategories VALUES (35, 10, 'Lavagem');
INSERT INTO tbl_subcategories VALUES (36, 10, 'Pedágio');
INSERT INTO tbl_subcategories VALUES (37, 21, 'Ferramenta');
INSERT INTO tbl_subcategories VALUES (38, 21, 'Host');
INSERT INTO tbl_subcategories VALUES (39, 21, 'Streaming');

INSERT INTO tbl_user_preferences (preference_id, is_light_theme) VALUES (1, 1);